version: '3.8'

services:
  oolio-api-ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=oolio
    networks:
      - oolio-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oolio
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - oolio-network

volumes:
  db-data:

networks:
  oolio-network:
    driver: bridge